name: windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
        vs-version: '17.9'

    - name: Replace multiple files
      uses: richardrigutins/replace-in-files@v2
      with:
        files: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\Microsoft.VCToolsVersion.v143.default.props'
        search-text: '14.38.33130'
        replacement-text: '14.39.33519'
        encoding: 'utf8'

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64

    - name: Build Release
      run: cmake --build build --config Release

    - name: Build Debug
      run: cmake --build build --config Debug

    - name: Pack NuGet
      run: nuget pack shapedbyiris.aec3.nuspec -p version=$((Get-Date).tostring("yyyy.MMdd.HHmm"))

    - name: Publish NuGet
      if: github.event_name != 'pull_request'
      run: |
        nuget sources Add -Name github -Source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json -Username ${{github.repository_owner}} -Password ${{github.token}}
        nuget push *.nupkg -Source github -SkipDuplicate -ApiKey ${{github.token}}
